{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rick-and-morty-chart.fullname" . }}-ingress
  labels:
    app.kubernetes.io/name: {{ include "rick-and-morty-chart.name" . }}
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "rick-and-morty-chart.fullname" . }}-service
                port:
                  number: {{ .Values.service.port }}
{{- end }}
