replicaCount: 1

image:
  repository: rick-and-morty-app
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: true
  hostname: "rick.local"
  path: "/"

resources: {}