name: main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Kind cluster
        uses: helm/kind-action@v1.2.0
        with:
          version: v0.17.0

      - name: Build Docker image
        run: |
          docker build -t rick-and-morty-app:latest .

      - name: Load Docker image into Kind
        run: |
          kind load docker-image rick-and-morty-app:latest

      - name: Deploy using kubectl
        run: |
          kubectl apply -f yamls/Deployment.yaml
          kubectl apply -f yamls/Service.yaml
          kubectl apply -f yamls/Ingress.yaml

      - name: Test endpoints
        run: |
          # Wait a few seconds for the Pods to become ready
          sleep 10

          # Check pods status
          kubectl get pods

          # Port-forward to local port 5000
          kubectl port-forward svc/rick-and-morty-service 5000:80 &
          sleep 5

          # Test the healthcheck endpoint
          curl http://localhost:5000/healthcheck

          # Test the characters endpoint
          curl http://localhost:5000/characters
